# Copyright Red Hat

apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .multicontent.Namespace }}"
---
# Copyright Red Hat

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .multicontent.ServiceAccount }}"
  namespace: "{{ .multicontent.Namespace }}"
secrets:
- name: mysecret
---